# Generated by Django 5.0.1 on 2024-02-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('email', models.EmailField(max_length=255, verbose_name='Email address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('auth_id', models.CharField(max_length=100, unique=True)),
                ('birthday', models.CharField(blank=True, max_length=20, verbose_name='Birthday')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Company name')),
                ('family_name', models.CharField(blank=True, max_length=255, verbose_name='Family name')),
                ('given_name', models.CharField(blank=True, max_length=255, verbose_name='Given name')),
                ('nickname', models.CharField(blank=True, max_length=255, verbose_name='Nickname')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone number')),
                ('reference_id', models.CharField(blank=True, max_length=255, verbose_name='Reference ID')),
            ],
        ),
    ]
